[passwords]
alice = "alice"
bob = "bob"
user1 = "user1"
michael = "michael"

[roles]
alice = "admin"
bob = "user"
user1 = "user"
michael = "user"

[permissions]
alice = [ "Home", "Info", "Customers", "Admin",]
bob = [ "Home", "Info",]
user1 = [ "Home",]
michael = [ "Home", "Profile",]

[active_users]
alice = true
bob = true
user1 = false
michael = true

[profile.alice]
name = "Alice Foo"
password = "alice"

[profile.bob]
name = "Bob Bar"
password = "bob"

[profile.user1]
name = "User One"
password = "user1"

[profile.michael]
name = "Michael Tinnacher"
password = "michael"
